# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0002_auto_20161221_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scopes.Resource')),
            ],
            options={
                'ordering': ('resource__name',),
                'verbose_name_plural': 'Scopes',
            },
        ),
    ]
