"""
Compose site-settings for {{ deployment_name }} deployment.

Generated by './manage.py startdeployment' using Django {{ django_version }} and Compose (no version yet :D).

For more information on this file, see
https://docs.djangoproject.com/en/{{ docs_version }}/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/
"""

import os

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/{{ docs_version }}/howto/deployment/checklist/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/{{ docs_version }}/howto/static-files/

# ----------------------
# Tutaj komentarz
# ---------------------
# STATIC_ROOT = os.path.join(BASE_DIR, '..', 'static')
# MEDIA_ROOT = os.path.join(BASE_DIR, '..', 'media')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '{{ secret_key }}'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Database
# https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#databases

# ----------------------
# Tutaj komentarz
# ---------------------
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, '..', 'db.sqlite3'),
#     },
#     'compose': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, '..', 'compose.sqlite3'),
#     }

# }

ALLOWED_HOSTS = []



